version: "3.8"
services:
  my-remix-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      WEBSITE_URL: ${WEBSITE_URL}
      NOVULO_REST_API: ${NOVULO_REST_API}
      GTM_ID: ${GTM_ID}
    volumes:
      - ./:/app
